INSERT INTO products (name, slug, category, size, sku, price) VALUES
  ('Kemeja Formal Pria', 'kemeja-formal-pria-s', 'dewasa', 'S', 'DW-KEMEJAF-S', 185000),
  ('Kemeja Formal Pria', 'kemeja-formal-pria-m', 'dewasa', 'M', 'DW-KEMEJAF-M', 185000),
  ('Kemeja Formal Pria', 'kemeja-formal-pria-l', 'dewasa', 'L', 'DW-KEMEJAF-L', 185000),
  ('Kemeja Formal Pria', 'kemeja-formal-pria-xl', 'dewasa', 'XL', 'DW-KEMEJAF-XL', 185000),
  ('Kemeja Formal Pria', 'kemeja-formal-pria-xxl', 'dewasa', 'XXL', 'DW-KEMEJAF-XXL', 185000),
  ('Kemeja Casual Pria', 'kemeja-casual-pria-s', 'dewasa', 'S', 'DW-KEMEJAC-S', 125000),
  ('Kemeja Casual Pria', 'kemeja-casual-pria-m', 'dewasa', 'M', 'DW-KEMEJAC-M', 125000),
  ('Kemeja Casual Pria', 'kemeja-casual-pria-l', 'dewasa', 'L', 'DW-KEMEJAC-L', 125000),
  ('Kemeja Casual Pria', 'kemeja-casual-pria-xl', 'dewasa', 'XL', 'DW-KEMEJAC-XL', 125000),
  ('Kaos Polos Pria', 'kaos-polos-pria-s', 'dewasa', 'S', 'DW-KAOSPOLS-S', 75000),
  ('Kaos Polos Pria', 'kaos-polos-pria-m', 'dewasa', 'M', 'DW-KAOSPOLS-M', 75000),
  ('Kaos Polos Pria', 'kaos-polos-pria-l', 'dewasa', 'L', 'DW-KAOSPOLS-L', 75000),
  ('Kaos Polos Pria', 'kaos-polos-pria-xl', 'dewasa', 'XL', 'DW-KAOSPOLS-XL', 75000),
  ('Kaos Polos Pria', 'kaos-polos-pria-xxl', 'dewasa', 'XXL', 'DW-KAOSPOLS-XXL', 75000),
  ('Kaos Polo Pria', 'kaos-polo-pria-s', 'dewasa', 'S', 'DW-KAOSPOL-S', 110000),
  ('Kaos Polo Pria', 'kaos-polo-pria-m', 'dewasa', 'M', 'DW-KAOSPOL-M', 110000),
  ('Kaos Polo Pria', 'kaos-polo-pria-l', 'dewasa', 'L', 'DW-KAOSPOL-L', 110000),
  ('Kaos Polo Pria', 'kaos-polo-pria-xl', 'dewasa', 'XL', 'DW-KAOSPOL-XL', 110000),
  ('Celana Chino Pria', 'celana-chino-pria-28', 'dewasa', '28', 'DW-CELANAC-28', 195000),
  ('Celana Chino Pria', 'celana-chino-pria-30', 'dewasa', '30', 'DW-CELANAC-30', 195000),
  ('Celana Chino Pria', 'celana-chino-pria-32', 'dewasa', '32', 'DW-CELANAC-32', 195000),
  ('Celana Chino Pria', 'celana-chino-pria-34', 'dewasa', '34', 'DW-CELANAC-34', 195000),
  ('Celana Chino Pria', 'celana-chino-pria-36', 'dewasa', '36', 'DW-CELANAC-36', 195000),
  ('Celana Jeans Pria', 'celana-jeans-pria-28', 'dewasa', '28', 'DW-CELANAJ-28', 225000),
  ('Celana Jeans Pria', 'celana-jeans-pria-30', 'dewasa', '30', 'DW-CELANAJ-30', 225000),
  ('Celana Jeans Pria', 'celana-jeans-pria-32', 'dewasa', '32', 'DW-CELANAJ-32', 225000),
  ('Celana Jeans Pria', 'celana-jeans-pria-34', 'dewasa', '34', 'DW-CELANAJ-34', 225000),
  ('Celana Jeans Pria', 'celana-jeans-pria-36', 'dewasa', '36', 'DW-CELANAJ-36', 225000),
  ('Celana Pendek Pria', 'celana-pendek-pria-s', 'dewasa', 'S', 'DW-CELANAP-S', 95000),
  ('Celana Pendek Pria', 'celana-pendek-pria-m', 'dewasa', 'M', 'DW-CELANAP-M', 95000),
  ('Celana Pendek Pria', 'celana-pendek-pria-l', 'dewasa', 'L', 'DW-CELANAP-L', 95000),
  ('Celana Pendek Pria', 'celana-pendek-pria-xl', 'dewasa', 'XL', 'DW-CELANAP-XL', 95000),
  ('Jaket Bomber Pria', 'jaket-bomber-pria-s', 'dewasa', 'S', 'DW-JAKETBO-S', 350000),
  ('Jaket Bomber Pria', 'jaket-bomber-pria-m', 'dewasa', 'M', 'DW-JAKETBO-M', 350000),
  ('Jaket Bomber Pria', 'jaket-bomber-pria-l', 'dewasa', 'L', 'DW-JAKETBO-L', 350000),
  ('Jaket Bomber Pria', 'jaket-bomber-pria-xl', 'dewasa', 'XL', 'DW-JAKETBO-XL', 350000),
  ('Hoodie Pria', 'hoodie-pria-s', 'dewasa', 'S', 'DW-HOODIEP-S', 275000),
  ('Hoodie Pria', 'hoodie-pria-m', 'dewasa', 'M', 'DW-HOODIEP-M', 275000),
  ('Hoodie Pria', 'hoodie-pria-l', 'dewasa', 'L', 'DW-HOODIEP-L', 275000),
  ('Hoodie Pria', 'hoodie-pria-xl', 'dewasa', 'XL', 'DW-HOODIEP-XL', 275000),
  ('Hoodie Pria', 'hoodie-pria-xxl', 'dewasa', 'XXL', 'DW-HOODIEP-XXL', 275000),
  ('Blazer Pria', 'blazer-pria-s', 'dewasa', 'S', 'DW-BLAZERP-S', 450000),
  ('Blazer Pria', 'blazer-pria-m', 'dewasa', 'M', 'DW-BLAZERP-M', 450000),
  ('Blazer Pria', 'blazer-pria-l', 'dewasa', 'L', 'DW-BLAZERP-L', 450000),
  ('Blazer Pria', 'blazer-pria-xl', 'dewasa', 'XL', 'DW-BLAZERP-XL', 450000),
  ('Dress Casual Wanita', 'dress-casual-wanita-xs', 'dewasa', 'XS', 'DW-DRESSCA-XS', 175000),
  ('Dress Casual Wanita', 'dress-casual-wanita-s', 'dewasa', 'S', 'DW-DRESSCA-S', 175000),
  ('Dress Casual Wanita', 'dress-casual-wanita-m', 'dewasa', 'M', 'DW-DRESSCA-M', 175000),
  ('Dress Casual Wanita', 'dress-casual-wanita-l', 'dewasa', 'L', 'DW-DRESSCA-L', 175000),
  ('Dress Casual Wanita', 'dress-casual-wanita-xl', 'dewasa', 'XL', 'DW-DRESSCA-XL', 175000),
  ('Dress Formal Wanita', 'dress-formal-wanita-xs', 'dewasa', 'XS', 'DW-DRESSFO-XS', 285000),
  ('Dress Formal Wanita', 'dress-formal-wanita-s', 'dewasa', 'S', 'DW-DRESSFO-S', 285000),
  ('Dress Formal Wanita', 'dress-formal-wanita-m', 'dewasa', 'M', 'DW-DRESSFO-M', 285000),
  ('Dress Formal Wanita', 'dress-formal-wanita-l', 'dewasa', 'L', 'DW-DRESSFO-L', 285000),
  ('Blouse Wanita', 'blouse-wanita-xs', 'dewasa', 'XS', 'DW-BLOUSEW-XS', 135000),
  ('Blouse Wanita', 'blouse-wanita-s', 'dewasa', 'S', 'DW-BLOUSEW-S', 135000),
  ('Blouse Wanita', 'blouse-wanita-m', 'dewasa', 'M', 'DW-BLOUSEW-M', 135000),
  ('Blouse Wanita', 'blouse-wanita-l', 'dewasa', 'L', 'DW-BLOUSEW-L', 135000),
  ('Blouse Wanita', 'blouse-wanita-xl', 'dewasa', 'XL', 'DW-BLOUSEW-XL', 135000),
  ('Kaos Wanita', 'kaos-wanita-xs', 'dewasa', 'XS', 'DW-KAOSWAN-XS', 85000),
  ('Kaos Wanita', 'kaos-wanita-s', 'dewasa', 'S', 'DW-KAOSWAN-S', 85000),
  ('Kaos Wanita', 'kaos-wanita-m', 'dewasa', 'M', 'DW-KAOSWAN-M', 85000),
  ('Kaos Wanita', 'kaos-wanita-l', 'dewasa', 'L', 'DW-KAOSWAN-L', 85000),
  ('Celana Kulot Wanita', 'celana-kulot-wanita-s', 'dewasa', 'S', 'DW-CELANAK-S', 155000),
  ('Celana Kulot Wanita', 'celana-kulot-wanita-m', 'dewasa', 'M', 'DW-CELANAK-M', 155000),
  ('Celana Kulot Wanita', 'celana-kulot-wanita-l', 'dewasa', 'L', 'DW-CELANAK-L', 155000),
  ('Celana Kulot Wanita', 'celana-kulot-wanita-xl', 'dewasa', 'XL', 'DW-CELANAK-XL', 155000),
  ('Rok Midi Wanita', 'rok-midi-wanita-xs', 'dewasa', 'XS', 'DW-ROKMIDI-XS', 145000),
  ('Rok Midi Wanita', 'rok-midi-wanita-s', 'dewasa', 'S', 'DW-ROKMIDI-S', 145000),
  ('Rok Midi Wanita', 'rok-midi-wanita-m', 'dewasa', 'M', 'DW-ROKMIDI-M', 145000),
  ('Rok Midi Wanita', 'rok-midi-wanita-l', 'dewasa', 'L', 'DW-ROKMIDI-L', 145000),
  ('Cardigan Wanita', 'cardigan-wanita-s', 'dewasa', 'S', 'DW-CARDIGAN-S', 195000),
  ('Cardigan Wanita', 'cardigan-wanita-m', 'dewasa', 'M', 'DW-CARDIGAN-M', 195000),
  ('Cardigan Wanita', 'cardigan-wanita-l', 'dewasa', 'L', 'DW-CARDIGAN-L', 195000),
  ('Cardigan Wanita', 'cardigan-wanita-xl', 'dewasa', 'XL', 'DW-CARDIGAN-XL', 195000),
  ('Jaket Denim Wanita', 'jaket-denim-wanita-xs', 'dewasa', 'XS', 'DW-JAKETDE-XS', 320000),
  ('Jaket Denim Wanita', 'jaket-denim-wanita-s', 'dewasa', 'S', 'DW-JAKETDE-S', 320000),
  ('Jaket Denim Wanita', 'jaket-denim-wanita-m', 'dewasa', 'M', 'DW-JAKETDE-M', 320000),
  ('Jaket Denim Wanita', 'jaket-denim-wanita-l', 'dewasa', 'L', 'DW-JAKETDE-L', 320000),
  ('Jaket Denim Wanita', 'jaket-denim-wanita-xl', 'dewasa', 'XL', 'DW-JAKETDE-XL', 320000),
  ('Legging Wanita', 'legging-wanita-s', 'dewasa', 'S', 'DW-LEGGING-S', 95000),
  ('Legging Wanita', 'legging-wanita-m', 'dewasa', 'M', 'DW-LEGGING-M', 95000),
  ('Legging Wanita', 'legging-wanita-l', 'dewasa', 'L', 'DW-LEGGING-L', 95000),
  ('Legging Wanita', 'legging-wanita-xl', 'dewasa', 'XL', 'DW-LEGGING-XL', 95000),
  ('Sweater Wanita', 'sweater-wanita-xs', 'dewasa', 'XS', 'DW-SWEATER-XS', 215000),
  ('Sweater Wanita', 'sweater-wanita-s', 'dewasa', 'S', 'DW-SWEATER-S', 215000),
  ('Sweater Wanita', 'sweater-wanita-m', 'dewasa', 'M', 'DW-SWEATER-M', 215000),
  ('Sweater Wanita', 'sweater-wanita-l', 'dewasa', 'L', 'DW-SWEATER-L', 215000),
  ('Kaos Anak Laki', 'kaos-anak-laki-23', 'anak', '2-3thn', 'AK-KAOSANA-2-3thn', 65000),
  ('Kaos Anak Laki', 'kaos-anak-laki-34', 'anak', '3-4thn', 'AK-KAOSANA-3-4thn', 65000),
  ('Kaos Anak Laki', 'kaos-anak-laki-45', 'anak', '4-5thn', 'AK-KAOSANA-4-5thn', 65000),
  ('Kaos Anak Laki', 'kaos-anak-laki-56', 'anak', '5-6thn', 'AK-KAOSANA-5-6thn', 65000),
  ('Kaos Anak Laki', 'kaos-anak-laki-67', 'anak', '6-7thn', 'AK-KAOSANA-6-7thn', 65000),
  ('Kaos Anak Perempuan', 'kaos-anak-perempuan-23', 'anak', '2-3thn', 'AK-KAOSANA-2-3thn', 65000),
  ('Kaos Anak Perempuan', 'kaos-anak-perempuan-34', 'anak', '3-4thn', 'AK-KAOSANA-3-4thn', 65000),
  ('Kaos Anak Perempuan', 'kaos-anak-perempuan-45', 'anak', '4-5thn', 'AK-KAOSANA-4-5thn', 65000),
  ('Kaos Anak Perempuan', 'kaos-anak-perempuan-56', 'anak', '5-6thn', 'AK-KAOSANA-5-6thn', 65000),
  ('Kaos Anak Perempuan', 'kaos-anak-perempuan-67', 'anak', '6-7thn', 'AK-KAOSANA-6-7thn', 65000),
  ('Kemeja Anak Laki', 'kemeja-anak-laki-34', 'anak', '3-4thn', 'AK-KEMEJAA-3-4thn', 95000),
  ('Kemeja Anak Laki', 'kemeja-anak-laki-45', 'anak', '4-5thn', 'AK-KEMEJAA-4-5thn', 95000),
  ('Kemeja Anak Laki', 'kemeja-anak-laki-56', 'anak', '5-6thn', 'AK-KEMEJAA-5-6thn', 95000),
  ('Kemeja Anak Laki', 'kemeja-anak-laki-67', 'anak', '6-7thn', 'AK-KEMEJAA-6-7thn', 95000),
  ('Kemeja Anak Laki', 'kemeja-anak-laki-78', 'anak', '7-8thn', 'AK-KEMEJAA-7-8thn', 95000),
  ('Dress Anak Perempuan', 'dress-anak-perempuan-23', 'anak', '2-3thn', 'AK-DRESSAN-2-3thn', 115000),
  ('Dress Anak Perempuan', 'dress-anak-perempuan-34', 'anak', '3-4thn', 'AK-DRESSAN-3-4thn', 115000),
  ('Dress Anak Perempuan', 'dress-anak-perempuan-45', 'anak', '4-5thn', 'AK-DRESSAN-4-5thn', 115000),
  ('Dress Anak Perempuan', 'dress-anak-perempuan-56', 'anak', '5-6thn', 'AK-DRESSAN-5-6thn', 115000),
  ('Celana Panjang Anak', 'celana-panjang-anak-23', 'anak', '2-3thn', 'AK-CELANAP-2-3thn', 85000),
  ('Celana Panjang Anak', 'celana-panjang-anak-34', 'anak', '3-4thn', 'AK-CELANAP-3-4thn', 85000),
  ('Celana Panjang Anak', 'celana-panjang-anak-45', 'anak', '4-5thn', 'AK-CELANAP-4-5thn', 85000),
  ('Celana Panjang Anak', 'celana-panjang-anak-56', 'anak', '5-6thn', 'AK-CELANAP-5-6thn', 85000),
  ('Celana Panjang Anak', 'celana-panjang-anak-67', 'anak', '6-7thn', 'AK-CELANAP-6-7thn', 85000),
  ('Celana Pendek Anak', 'celana-pendek-anak-23', 'anak', '2-3thn', 'AK-CELANAPK-2-3thn', 65000),
  ('Celana Pendek Anak', 'celana-pendek-anak-34', 'anak', '3-4thn', 'AK-CELANAPK-3-4thn', 65000),
  ('Celana Pendek Anak', 'celana-pendek-anak-45', 'anak', '4-5thn', 'AK-CELANAPK-4-5thn', 65000),
  ('Celana Pendek Anak', 'celana-pendek-anak-56', 'anak', '5-6thn', 'AK-CELANAPK-5-6thn', 65000),
  ('Jaket Anak', 'jaket-anak-34', 'anak', '3-4thn', 'AK-JAKETAN-3-4thn', 175000),
  ('Jaket Anak', 'jaket-anak-45', 'anak', '4-5thn', 'AK-JAKETAN-4-5thn', 175000),
  ('Jaket Anak', 'jaket-anak-56', 'anak', '5-6thn', 'AK-JAKETAN-5-6thn', 175000),
  ('Jaket Anak', 'jaket-anak-67', 'anak', '6-7thn', 'AK-JAKETAN-6-7thn', 175000),
  ('Jaket Anak', 'jaket-anak-78', 'anak', '7-8thn', 'AK-JAKETAN-7-8thn', 175000),
  ('Hoodie Anak', 'hoodie-anak-34', 'anak', '3-4thn', 'AK-HOODIEA-3-4thn', 145000),
  ('Hoodie Anak', 'hoodie-anak-45', 'anak', '4-5thn', 'AK-HOODIEA-4-5thn', 145000),
  ('Hoodie Anak', 'hoodie-anak-56', 'anak', '5-6thn', 'AK-HOODIEA-5-6thn', 145000),
  ('Hoodie Anak', 'hoodie-anak-67', 'anak', '6-7thn', 'AK-HOODIEA-6-7thn', 145000),
  ('Hoodie Anak', 'hoodie-anak-78', 'anak', '7-8thn', 'AK-HOODIEA-7-8thn', 145000),
  ('Setelan Anak Laki', 'setelan-anak-laki-23', 'anak', '2-3thn', 'AK-SETELANL-2-3thn', 135000),
  ('Setelan Anak Laki', 'setelan-anak-laki-34', 'anak', '3-4thn', 'AK-SETELANL-3-4thn', 135000),
  ('Setelan Anak Laki', 'setelan-anak-laki-45', 'anak', '4-5thn', 'AK-SETELANL-4-5thn', 135000),
  ('Setelan Anak Laki', 'setelan-anak-laki-56', 'anak', '5-6thn', 'AK-SETELANL-5-6thn', 135000),
  ('Setelan Anak Perempuan', 'setelan-anak-perempuan-23', 'anak', '2-3thn', 'AK-SETELANP-2-3thn', 135000),
  ('Setelan Anak Perempuan', 'setelan-anak-perempuan-34', 'anak', '3-4thn', 'AK-SETELANP-3-4thn', 135000),
  ('Setelan Anak Perempuan', 'setelan-anak-perempuan-45', 'anak', '4-5thn', 'AK-SETELANP-4-5thn', 135000),
  ('Setelan Anak Perempuan', 'setelan-anak-perempuan-56', 'anak', '5-6thn', 'AK-SETELANP-5-6thn', 135000),
  ('Rok Anak Perempuan', 'rok-anak-perempuan-23', 'anak', '2-3thn', 'AK-ROKANAK-2-3thn', 85000),
  ('Rok Anak Perempuan', 'rok-anak-perempuan-34', 'anak', '3-4thn', 'AK-ROKANAK-3-4thn', 85000),
  ('Rok Anak Perempuan', 'rok-anak-perempuan-45', 'anak', '4-5thn', 'AK-ROKANAK-4-5thn', 85000),
  ('Rok Anak Perempuan', 'rok-anak-perempuan-56', 'anak', '5-6thn', 'AK-ROKANAK-5-6thn', 85000),
  ('Piyama Anak', 'piyama-anak-23', 'anak', '2-3thn', 'AK-PIYAMAA-2-3thn', 110000),
  ('Piyama Anak', 'piyama-anak-34', 'anak', '3-4thn', 'AK-PIYAMAA-3-4thn', 110000),
  ('Piyama Anak', 'piyama-anak-45', 'anak', '4-5thn', 'AK-PIYAMAA-4-5thn', 110000),
  ('Piyama Anak', 'piyama-anak-56', 'anak', '5-6thn', 'AK-PIYAMAA-5-6thn', 110000),
  ('Piyama Anak', 'piyama-anak-67', 'anak', '6-7thn', 'AK-PIYAMAA-6-7thn', 110000)
ON CONFLICT (sku) DO NOTHING;
